name: Build MangoJuice AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: "mangojuice build"
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: "mangojuice build"
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm \
          appstream \
          base-devel \
          cmocka \
          dbus \
          fmt \
          fontconfig \
          gcc-libs \
          gettext \
          git \
          glew \
          glfw \
          glib2 \
          glslang \
          gtk4 \
          hicolor-icon-theme \
          libadwaita \
          libgee \
          libglvnd \
          libsodium \
          libx11 \
          libxkbcommon \
          libxrandr \
          meson \
          ninja \
          nlohmann-json \
          patchelf \
          python \
          python-mako \
          python-matplotlib \
          python-numpy \
          strace \
          vala \
          vulkan-headers \
          vulkan-tools \
          wget \
          xorg-server-xvfb \
          zsync

    - name: Build mangohud
      run: |
        echo "Building mangohud..."
        echo "---------------------------------------------------------------"
        sed -i 's|EUID == 0|EUID == 69|g' /usr/bin/makepkg
        mkdir -p /usr/local/bin
        cp /usr/bin/makepkg /usr/local/bin
        
        sed -i -e 's|-O2|-Os|' \
        	-e 's|MAKEFLAGS=.*|MAKEFLAGS="-j$(nproc)"|' \
        	-e 's|#MAKEFLAGS|MAKEFLAGS|' \
        	/etc/makepkg.conf
        
        cat /etc/makepkg.conf
        
        git clone https://gitlab.archlinux.org/archlinux/packaging/packages/mangohud.git ./mangohud
        ( cd ./mangohud
        	sed -i -e "s|x86_64|$(uname -m)|" \
        		-e 's|-Dmangohudctl=true|-Dmangohudctl=true -Dwith_xnvctrl=disabled|' \
        		-e '/libxnvctrl/d' ./PKGBUILD
        	makepkg -f
        	ls -la .
        	pacman --noconfirm -U *.pkg.tar.*
        )
        rm -rf ./mangohud
  
    - name: Build and install MangoJuice
      run: |
        meson setup build --prefix=/usr
        ninja -C build
        sudo ninja -C build install
        
    - name: Create AppImage
      run: |
        chmod +x ./build-aux/mangojuice-appimage.sh
        ./build-aux/mangojuice-appimage.sh
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: MangoJuice-AppImagename-${{ matrix.arch }}
        path: MangoJuice-*.AppImage
